# Generated by Django 4.2 on 2024-07-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.IntegerField(default=1)),
                ('JobRole', models.CharField(max_length=50)),
                ('JobLoc', models.CharField(blank=True, max_length=50, null=True)),
                ('Source', models.CharField(blank=True, max_length=50, null=True)),
                ('JobTy', models.CharField(blank=True, max_length=50, null=True)),
                ('Contact', models.CharField(blank=True, max_length=20, null=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone_interview', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3, null=True)),
                ('status', models.CharField(blank=True, choices=[('Rejected', 'Rejected'), ('Satisfactory', 'Satisfactory'), ('On Hold', 'On Hold')], max_length=50, null=True)),
                ('first_interview', models.DateField(blank=True, null=True)),
                ('first_interview_status', models.CharField(blank=True, choices=[('Cleared', 'Cleared'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold')], max_length=50, null=True)),
                ('second_interview', models.DateField(blank=True, null=True)),
                ('second_interview_status', models.CharField(blank=True, choices=[('Cleared', 'Cleared'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold')], max_length=50, null=True)),
                ('final_interview', models.DateField(blank=True, null=True)),
                ('final_interview_status', models.CharField(blank=True, choices=[('Hired', 'Hired'), ('Rejected', 'Rejected')], max_length=50, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('ctc', models.CharField(blank=True, default='0', max_length=20, null=True)),
            ],
        ),
    ]
